---
version: 2
configuration:
  type: object
  fields:
    message:
      name: Discount message
      type: single_line_text_field
    vipTag:
      name: VIP customer tag
      type: single_line_text_field
    discountAmount:
      name: Discount amount
      type: number_decimal
