name = "VIP discount"
type = "order_discount_type"
title = "VIP discount"

[functions.ui]
createPath = "/vip/new"
detailsPath = "/vip/:id"

# TODO: When the metaobject format is finalized, update this to match script.config.yml
[functions.metaObject]
fields = {}
type = "object"
