[package]
name = "web3_discount"
version = "1.0.0"
edition = "2021"
include = ["*.graphql"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.13", features = ["derive"] }
graphql_client = "0.10.0"

[profile.release]
lto = true
opt-level = 's'
strip = true
