---
version: '2'
title: Merchandise discount types default script
configuration:
  type: object
  fields:
    value:
      type: number_decimal
      name: Value
      validations:
      - name: min
        value: '0'
      - name: max
        value: '100'

