# XXX THIS IS HERE TEMPORARILY FOR USE WITH CLI 2.0. REMOVE BEFORE SHIPPING!
---
project_type: :script
organization_id: 0
title: Product Discount
extension_point_type: product_discounts
language: wasm
app_bridge_create_path: /product-discount/new
app_bridge_details_path: /product-discount/:id
