name = "Product Discount"
type = "product_discounts"
buildWasmPath = "target/wasm32-wasi/release/product-discount.wasm"
version = "2"
api_version = "2022-07"

[meta_object]
type = "object"

[meta_object.fields]

[ui.paths]
create = "/product-discount/new"
details = "/product-discount/:id"

[commands]
build = "cargo wasi build --release"
