name = "move to last delivery option by title"
type = "delivery_customization"
title = "move to last delivery option by title"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/delivery_customization_move_to_last_by_title.wasm"
