name = "Shipping Discount"
type = "shipping_discounts"
version = "2"
api_version = "2022-07"

[meta_object]
type = "object"

[meta_object.fields]

[ui.paths]
create = "/shipping-discount/new"
details = "/shipping-discount/:id"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/shipping-discount.wasm"
