name = "rename all payments"
type = "payment_customization"
title = "rename all payment"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/rename_all_payments.wasm"