name = "product-discount-rust"
type = "product_discounts"
api_version = "2023-01"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/product-discount.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/volume/:functionId/new"
details = "/volume/:functionId/:id"
