name = "move to last delivery option by title"
type = "delivery_customization"
title = "move to last delivery option by title"
api_version = "2023-04"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/delivery_customization_move_to_last_by_title.wasm"

[ui.paths]
create = "/reorder/:functionId/new"
details = "/reorder/:functionId/:id"
