name = "Hide Payment By Name and Cart Subtotal"
type = "payment_customization"
api_version = "2023-04"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/hide-payment-by-name-and-cart-subtotal.wasm"

[ui.paths]
create = "/hide/:functionId/new"
details = "/hide/:functionId/:id"
