name = "rename delivery option by title"
type = "delivery_customization"
title = "rename delivery option by title"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/delivery_customization_rename_by_title.wasm"
