api_version = "2023-04"
name = "delivery-customization-rust"
type = "delivery_customization"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/delivery-customization.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/delivery-customization/:functionId/new"
details = "/delivery-customization/:functionId/:id"
