# XXX THIS IS HERE TEMPORARILY FOR USE WITH CLI 2.0. REMOVE BEFORE SHIPPING!
---
project_type: :script
organization_id: 0
title: Order Discount
extension_point_type: order_discounts
language: wasm
app_bridge_create_path: /order-discount/new
app_bridge_details_path: /order-discount/:id
