[package]
edition = "2021"
include = ["*.graphql"]
name = "order_discounts"
version = "1.0.0"

[dependencies]
serde = {version = "1.0.13", features = ["derive"]}
serde_json = "1.0"
serde_with = "1.13.0"

[profile.release]
lto = true
opt-level = 's'
strip = true
