name = "Order Discount"
type = "order_discounts"
version = "2"
api_version = "2022-07"

[meta_object]
type = "object"

[meta_object.fields]

[ui.paths]
create = "/order-discount/new"
details = "/order-discount/:id"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/order-discount.wasm"
