[package]
edition = "2021"
name = "bundle-discount"
version = "0.1.0"

[dependencies]
graphql_client = "0.10.0"
serde = {version = "1.0.13", features = ["derive"]}
serde_json = "1.0"

[profile.release]
lto = true
opt-level = 's'
strip = true
