---
version: 2
configuration:
  type: object
  fields:
    message:
      name: Discount message
      type: single_line_text_field
    variantId:
      name: Variant ID
      type: variant_reference
    minimumQuantity:
      name: Minimum line item quantity
      type: number_integer
    discountPercentage:
      name: Discount percentage
      type: number_decimal
