name = "Bundle Discount"
title = "Bundle Discount"
type = "product_discount_type"

[functions.ui]
createPath = "/bundle-discount/new"
detailsPath = "/bundle-discount/:id"

# TODO: When the metaobject format is finalized, update this to match script.config.yml
[functions.metaObject]
fields = {}
type = "object"
