name = "cart merge expand"
type = "cart_transform"
title = "cart merge expand"
api_version = "2023-07"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/bundle_cart_transform.wasm"
