name = "hide delivery option by title"
type = "delivery_customization"
title = "hide delivery option by title"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/delivery_customization_hide_by_title.wasm"

[ui.paths]
create = "/hide/:functionId/new"
details = "/hide/:functionId/:id"
