name = "cart merge expand"
type = "cart_transform"
title = "cart merge expand"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/cart_merge_expand.wasm"
